### PR TITLE
Issue #143 cart checkout bugs

### LINKED ISSUE #143: <Cart-and-Checkout> Fix Bugs and Features
I need to fix the following issues and change the following functionality:

1. Fix cart so it updates when opened after adding a cart item.
2. Make the buy now button only take current product and proceed to checkout (need to change logic so checkout doesn't fetch cart but receives items on request).
3. Change code to use user_id for fetching a creating, (opposed to global creation).
4. Make sure before going to checkout quantity is valid and the item exists.
5. Display the name of the type (just called type) next to the name of the item.
6. Fix any styling needed on any pages. (Mainly responsive design)

This will fix small issues that make the user experience and flow of the app better.

### PR DESCRIPTION
**Pull request by devinbowler**
This is a big commit with small changes everywhere, read my commit and check everything before approval, it's late, I could have missed something.

### CODE REVIEW

File: backend/controllers/OrderController.js [hunk 1]
```diff
@@ -58,28 +55,44 @@ class OrderController {
...
+    }
   }
-}
 
+    /**
+   * Cancel (delete) an existing order.
+   * @param {Object} req - Express request object containing orderId in `req.params.id`.
+   * @param {Object} res - Express response object.
+   */
+  async cancelOrder(req, res) {
```
Comment (wnauda) [inline backend/controllers/OrderController.js:84]: I can't find a way to cancel an order in the app, is this currently being used?

**Review by wnauda — APPROVED** [review]
Functionality and UI are good, I think this can be merged.

File: backend/controllers/OrderController.js (hunk 1 above)
Comment (devinbowler) [reply backend/controllers/OrderController.js:84]: No, it was for Yukun to use on order history, but we don't have to use it.
